#---------------------------------------------------------
#  ____       _            _          _     _
# |  _ \ ___ | |_   ___  _| |    ___ | |__ | |__  _   _
# | |_) / _ \| | | | \ \/ / |   / _ \| '_ \| '_ \| | | |
# |  __/ (_) | | |_| |>  <| |__| (_) | |_) | |_) | |_| |
# |_|   \___/|_|\__,_/_/\_\_____\___/|_.__/|_.__/ \__, |
#                                                 |___/
#----------------------------------------------------------


fly-item:
  name: "&7Fly: &cUIT"
  lore:
    - "&7Rechter-klik om je fly aan te zetten!"
  slot: 6
  amount: 1



#  _____ __    _____ _____ _____
#  |   __|  |  |  _  |   __|   __|
#  |   __|  |__|     |  |  |__   |
#  |__|  |_____|__|__|_____|_____|

item-drop: false
item-pickup: false
fall-damage: false
block-brake: false
block-place: false